In [3]:
import os
import pandas as pd
from IPython.display import display

# Ubah nilai ini untuk mengganti subjek (contoh: 'SUB1', 'SUB2', dst.)
SUBJECT = 'SUB1'

# Ubah nilai ini untuk mengganti metrik target (contoh: 'cer', 'WER', 'BLEU-1', dll.)
TARGET_METRIC = 'cer'

PERCENTILES = [0, 10, 25, 35, 50, 65, 75, 85, 95, 100]

script_dir = os.getcwd()

file_templates = [
    "complete_metrics_{subject}_eq_3_0_fixed_hilbert_test_predictions_6_1.csv",
    "complete_metrics_{subject}_eq_3_0_hilbert_test_predictions_10_1_IndoGPT.csv",
    "complete_metrics_{subject}_eq_3_0_log-mel_test_predictions_6_1.csv",
    "complete_metrics_{subject}_eq_3_0_logmel_test_predictions_10_1_IndoGPT.csv",
    
    "complete_metrics_NOISE_BASELINE_{subject}_eq_3_0_fixed_hilbert_test_predictions_6_1.csv",
    "complete_metrics_NOISE_BASELINE_{subject}_eq_3_0_hilbert_test_predictions_10_1_IndoGPT.csv",
    "complete_metrics_NOISE_BASELINE_{subject}_eq_3_0_log-mel_test_predictions_6_1.csv",
    "complete_metrics_NOISE_BASELINE_{subject}_eq_3_0_logmel_test_predictions_10_1_IndoGPT.csv"
]

print(f"Menampilkan sampel prediksi pada persentil {TARGET_METRIC.upper()} untuk subjek: {SUBJECT}\n")

for template in file_templates:
    filename = template.format(subject=SUBJECT)
    filepath = os.path.join(script_dir, filename)
    
    print("=" * 110)
    print(f"📄 File: {filename}")
    print("=" * 110)
    
    if os.path.exists(filepath):
        try:
            df = pd.read_csv(filepath)
            
            req_cols = [TARGET_METRIC, 'sentence', 'prediction']
            if all(col in df.columns for col in req_cols):
                
                df_sorted = df.sort_values(by=TARGET_METRIC).reset_index(drop=True)
                
                results = []
                n_rows = len(df_sorted)
                
                if n_rows > 0:
                    for p in PERCENTILES:
                        # Rumus: (p / 100) * (total_baris - 1)
                        idx = int((p / 100.0) * (n_rows - 1))
                        row = df_sorted.iloc[idx]
                        
                        results.append({
                            'persentil': f"{p}",
                            TARGET_METRIC: round(row[TARGET_METRIC], 4),
                            'sentence': row['sentence'],
                            'prediction': row['prediction']
                        })
                    
                    df_result = pd.DataFrame(results)
                    display(df_result)
                else:
                    print("⚠️ File CSV kosong (tidak ada baris).")
            else:
                missing = [col for col in req_cols if col not in df.columns]
                print(f"⚠️ Peringatan: Kolom {missing} tidak ditemukan di dalam file ini.")
                
        except Exception as e:
            print(f"❌ Gagal membaca file: {e}")
    else:
        print(f"❌ File belum ditemukan di: {filepath}")
        
    print("\n")

Menampilkan sampel prediksi pada persentil CER untuk subjek: SUB1

==============================================================================================================
📄 File: complete_metrics_SUB1_eq_3_0_fixed_hilbert_test_predictions_6_1.csv
==============================================================================================================

,persentil,cer,sentence,prediction
0,0,52.6316,maaf saya terlambat,sayur saya perinya
1,10,65.0000,silakan beri tahu saya nama lengkap anda,sayur tidak mengalian
2,25,68.1818,kita akan bertemu lagi,saya tukan separ
3,35,70.2703,apa yang bisa kami lakukan untuk anda,silakan pintuk
4,50,73.6842,anda benar benar kakek yang murah hati,selamat sedang pintaku
5,65,75.7576,kamu tampak penuh energi hari ini,hari ini
6,75,77.7778,saya bukan seorang penjahat,tolong bisa menalang
7,85,80.5556,kamu benar benar menjadi lebih sehat,silama saya anda
8,95,82.7586,apakah anda sudah makan siang,saya tidak sengaja anda bisa mebas
9,100,82.7586,tolong segera pergi dari sini,pekerjaan anda

==============================================================================================================
📄 File: complete_metrics_SUB1_eq_3_0_hilbert_test_predictions_10_1_IndoGPT.csv
==============================================================================================================

,persentil,cer,sentence,prediction
0,0,53.1250,benar benar tidak bisa dipercaya,saya tidak bisa makan
1,10,62.9630,waktu berjalan begitu cepat,kami akan segera sampai
2,25,67.5000,silakan beri tahu saya nama lengkap anda,saya tidak bisa minta maaf
3,35,70.0000,saya tidak punya waktu luang sama sekali,kamu adalah orang yang humoris
4,50,72.2222,kamu benar benar menjadi lebih sehat,kamu adalah orang yang humoris
5,65,75.0000,dia bukan orang yang penting,anda bisa mencetaknya
6,75,81.0811,apa yang bisa kami lakukan untuk anda,kamu adalah orang yang humoris
7,85,84.0000,bagaimana harimu hari ini,kami akan bertanggung jawab
8,95,89.6552,tolong segera pergi dari sini,saya tidak bisa minta maaf
9,100,105.5556,cobalah besok pagi,saya tidak bisa minta maaf

==============================================================================================================
📄 File: complete_metrics_SUB1_eq_3_0_log-mel_test_predictions_6_1.csv
==============================================================================================================

,persentil,cer,sentence,prediction
0,0,62.5000,setelah makan saya merasa sangat kenyang,selamat benar saya bantu
1,10,68.1818,kita akan bertemu lagi,saya saya bantu
2,25,70.3704,saya bukan seorang penjahat,silakan tidak bertanya malam
3,35,74.0741,waktu berjalan begitu cepat,maku anda
4,50,77.5000,silakan beri tahu saya nama lengkap anda,semora menunya
5,65,80.0000,bagaimana harimu hari ini,sembua sedang biar
6,75,81.0811,apa yang bisa kami lakukan untuk anda,sialam siang
7,85,82.7586,tolong segera pergi dari sini,saya tidak berani menunya
8,95,87.5000,biar saya bantu ganti baterainya,maaf ilu
9,100,88.8889,cobalah besok pagi,silakan sedang menung

==============================================================================================================
📄 File: complete_metrics_SUB1_eq_3_0_logmel_test_predictions_10_1_IndoGPT.csv
==============================================================================================================

,persentil,cer,sentence,prediction
0,0,59.2593,saya bukan seorang penjahat,saya tidak akan minta maaf
1,10,59.4595,apa yang bisa kami lakukan untuk anda,saya tidak akan minta maaf
2,25,65.6250,benar benar tidak bisa dipercaya,saya tidak akan minta maaf
3,35,69.4444,kamu benar benar menjadi lebih sehat,kami akan segera sampai
4,50,71.8750,biar saya bantu ganti baterainya,saya tidak akan minta maaf
5,65,74.1935,sebaiknya kita sarapan sekarang,senang bertemu dengan anda
6,75,77.5000,saya tidak punya waktu luang sama sekali,teroris tidak menghargai kehidupan
7,85,94.7368,maaf saya terlambat,saya tidak akan minta maaf
8,95,104.0000,bagaimana harimu hari ini,selamat sore ada yang bisa saya bantu
9,100,111.1111,cobalah besok pagi,kamu terlihat luar biasa

==============================================================================================================
📄 File: complete_metrics_NOISE_BASELINE_SUB1_eq_3_0_fixed_hilbert_test_predictions_6_1.csv
==============================================================================================================

,persentil,cer,sentence,prediction
0,0,59.3750,biar saya bantu ganti baterainya,saya sangat siang
1,10,63.1579,maaf saya terlambat,saya akan pendat
2,25,72.2222,kamu benar benar menjadi lebih sehat,anda selamat sore anda
3,35,72.7273,kita akan bertemu lagi,saya kami untu
4,50,77.7778,waktu berjalan begitu cepat,saya risa sayurannya
5,65,81.0811,saya sedang terburu buru sampai jumpa,tidak seringa
6,75,84.2105,anda benar benar kakek yang murah hati,aku anda
7,85,85.7143,dia bukan orang yang penting,pekerjatu
8,95,89.6552,apakah anda sudah makan siang,menuris
9,100,89.6552,tolong segera pergi dari sini,selamat sore anda yang bisa saya anda

==============================================================================================================
📄 File: complete_metrics_NOISE_BASELINE_SUB1_eq_3_0_hilbert_test_predictions_10_1_IndoGPT.csv
==============================================================================================================

,persentil,cer,sentence,prediction
0,0,53.1250,benar benar tidak bisa dipercaya,saya tidak bisa minta maaf
1,10,54.5455,kita akan bertemu lagi,kami akan segera
2,25,65.5172,apakah anda sudah makan siang,saya tidak bisa minta maaf
3,35,67.5000,silakan beri tahu saya nama lengkap anda,saya tidak bisa minta maaf
4,50,68.4211,anda benar benar kakek yang murah hati,saya tidak bisa minta maaf
5,65,71.8750,biar saya bantu ganti baterainya,saya tidak bisa minta maaf
6,75,75.0000,dia bukan orang yang penting,kami akan segera
7,85,81.0811,saya sedang terburu buru sampai jumpa,anda bisa
8,95,89.6552,tolong segera pergi dari sini,saya tidak bisa minta maaf
9,100,111.1111,cobalah besok pagi,kami akan bertanggung jawab

==============================================================================================================
📄 File: complete_metrics_NOISE_BASELINE_SUB1_eq_3_0_log-mel_test_predictions_6_1.csv
==============================================================================================================

,persentil,cer,sentence,prediction
0,0,60.0000,silakan beri tahu saya nama lengkap anda,selamat sore nona anda
1,10,68.1818,kita akan bertemu lagi,sekarang berinya
2,25,73.6842,maaf saya terlambat,kami apan menelepo
3,35,75.0000,setelah makan saya merasa sangat kenyang,ada berangi malam ada
4,50,77.7778,waktu berjalan begitu cepat,kami apanya
5,65,80.0000,bagaimana harimu hari ini,anda berani menanya
6,75,81.2500,biar saya bantu ganti baterainya,menurutku anda
7,85,81.8182,kamu tampak penuh energi hari ini,saya unda
8,95,92.5000,saya tidak punya waktu luang sama sekali,separ
9,100,94.4444,cobalah besok pagi,maaf saya punda penal

==============================================================================================================
📄 File: complete_metrics_NOISE_BASELINE_SUB1_eq_3_0_logmel_test_predictions_10_1_IndoGPT.csv
==============================================================================================================

,persentil,cer,sentence,prediction
0,0,64.5161,sebaiknya kita sarapan sekarang,saya tidak akan minta maaf
1,10,65.0000,setelah makan saya merasa sangat kenyang,selamat sore ada yang bisa saya bantu
2,25,72.5000,saya tidak punya waktu luang sama sekali,selamat sore ada yang bisa saya bantu
3,35,73.6842,anda benar benar kakek yang murah hati,selamat sore ada yang bisa saya bantu
4,50,80.0000,bagaimana harimu hari ini,saya tidak akan minta maaf
5,65,86.2069,tolong segera pergi dari sini,selamat sore ada yang bisa saya bantu
6,75,88.8889,saya bukan seorang penjahat,selamat sore ada yang bisa dibantu
7,85,93.1034,apakah anda sudah makan siang,selamat sore ada yang bisa saya bantu
8,95,131.5789,maaf saya terlambat,selamat sore ada yang bisa saya bantu
9,100,161.1111,cobalah besok pagi,selamat sore ada yang bisa saya bantu

In [4]:
import os
import pandas as pd
from IPython.display import display

# Ubah nilai ini untuk mengganti subjek (contoh: 'SUB1', 'SUB2', dst.)
SUBJECT = 'all'

# Ubah nilai ini untuk mengganti metrik target (contoh: 'cer', 'WER', 'BLEU-1', dll.)
TARGET_METRIC = 'cer'

PERCENTILES = [0, 10, 25, 35, 50, 65, 75, 85, 95, 100]

script_dir = os.getcwd()

file_templates = [
    "complete_metrics_{subject}_eq_3_0_fixed_hilbert_test_predictions_1_1.csv",
    "complete_metrics_{subject}_eq_3_0_hilbert_test_predictions_2_1_IndoGPT.csv",
    "complete_metrics_{subject}_eq_3_0_log-mel_test_predictions_6_1.csv",
    "complete_metrics_{subject}_eq_3_0_logmel_test_predictions_10_1_IndoGPT.csv",
    
    "complete_metrics_NOISE_BASELINE_{subject}_eq_3_0_fixed_hilbert_test_predictions_1_1.csv",
    "complete_metrics_NOISE_BASELINE_{subject}_eq_3_0_hilbert_test_predictions_2_1_IndoGPT.csv",
    "complete_metrics_NOISE_BASELINE_{subject}_eq_3_0_log-mel_test_predictions_6_1.csv",
    "complete_metrics_NOISE_BASELINE_{subject}_eq_3_0_logmel_test_predictions_10_1_IndoGPT.csv"
]

print(f"Menampilkan sampel prediksi pada persentil {TARGET_METRIC.upper()} untuk subjek: {SUBJECT}\n")

for template in file_templates:
    filename = template.format(subject=SUBJECT)
    filepath = os.path.join(script_dir, filename)
    
    print("=" * 110)
    print(f"📄 File: {filename}")
    print("=" * 110)
    
    if os.path.exists(filepath):
        try:
            df = pd.read_csv(filepath)
            
            req_cols = [TARGET_METRIC, 'sentence', 'prediction']
            if all(col in df.columns for col in req_cols):
                
                df_sorted = df.sort_values(by=TARGET_METRIC).reset_index(drop=True)
                
                results = []
                n_rows = len(df_sorted)
                
                if n_rows > 0:
                    for p in PERCENTILES:
                        # Rumus: (p / 100) * (total_baris - 1)
                        idx = int((p / 100.0) * (n_rows - 1))
                        row = df_sorted.iloc[idx]
                        
                        results.append({
                            'persentil': f"{p}",
                            TARGET_METRIC: round(row[TARGET_METRIC], 4),
                            'sentence': row['sentence'],
                            'prediction': row['prediction']
                        })
                    
                    df_result = pd.DataFrame(results)
                    display(df_result)
                else:
                    print("⚠️ File CSV kosong (tidak ada baris).")
            else:
                missing = [col for col in req_cols if col not in df.columns]
                print(f"⚠️ Peringatan: Kolom {missing} tidak ditemukan di dalam file ini.")
                
        except Exception as e:
            print(f"❌ Gagal membaca file: {e}")
    else:
        print(f"❌ File belum ditemukan di: {filepath}")
        
    print("\n")

Menampilkan sampel prediksi pada persentil CER untuk subjek: all

==============================================================================================================
📄 File: complete_metrics_all_eq_3_0_fixed_hilbert_test_predictions_1_1.csv
==============================================================================================================

,persentil,cer,sentence,prediction
0,0,50.0000,maaf telah mengganggu anda,maaf membuat anda
1,10,66.6667,saya sangat menghargai saran anda,maaf membuat anda
2,25,71.4286,makanan di sana lumayan enak,maaf membuat anda
3,35,72.2222,terima kasih banyak atas undangannya,maaf membuat anda
4,50,75.0000,kamu benar benar menjadi lebih sehat,maaf membuat anda
5,65,75.8621,pilihan anda banyak sekali ya,maaf membuat anda
6,75,77.7778,saya punya nomornya di sini,maaf membuat anda
7,85,80.5556,apakah anda tertarik dengan komputer,maaf membuat anda
8,95,84.6154,sepertinya kamu sedang flu,maaf membuat anda
9,100,131.2500,mari kita bicara,maaf teman saya sedang sakit

==============================================================================================================
📄 File: complete_metrics_all_eq_3_0_hilbert_test_predictions_2_1_IndoGPT.csv
==============================================================================================================

,persentil,cer,sentence,prediction
0,0,53.5714,mari makan di luar malam ini,kami akan segera sampai
1,10,62.1622,saya sedang terburu buru sampai jumpa,kami akan segera sampai
2,25,68.7500,bagaimana kabarmu belakangan ini,kami akan segera sampai
3,35,70.0000,silakan beri tahu saya nama lengkap anda,kami akan segera sampai
4,50,72.4138,wasit sepertinya agak memihak,kami akan segera sampai
5,65,75.0000,makanan di sana lumayan enak,kami akan segera sampai
6,75,75.8621,tolong segera pergi dari sini,kami akan segera sampai
7,85,80.9524,kita pergi nanti saja,kami akan segera sampai
8,95,95.6522,kamu akan segera sembuh,anda terlihat luar biasa
9,100,118.7500,tentu saja boleh,kami akan segera sampai

==============================================================================================================
📄 File: complete_metrics_all_eq_3_0_log-mel_test_predictions_6_1.csv
==============================================================================================================

,persentil,cer,sentence,prediction
0,0,46.1538,kamu adalah teman sejatiku,kamu adalah pahlawan
1,10,65.5172,dia akan merasa sangat senang,anda benar benar
2,25,70.0000,aku akan mencintaimu selamanya,selamat datang datang
3,35,72.0000,apakah sarapan sudah siap,kamu adalah orang
4,50,74.0741,anda seharusnya merasa malu,kamu benar benar
5,65,76.0000,kapan anda biasanya tidur,selamat datang datang
6,75,77.7778,saya punya nomornya di sini,kamu benar benar
7,85,80.0000,mari ikut saya ke kantor untuk bicara lebih la...,kamu adalah orang
8,95,91.3043,kamu akan segera sembuh,apakah ada yang bisa dibantu
9,100,181.2500,tentu saja boleh,dia adalah orang yang bisa dibantu

==============================================================================================================
📄 File: complete_metrics_all_eq_3_0_logmel_test_predictions_10_1_IndoGPT.csv
==============================================================================================================

,persentil,cer,sentence,prediction
0,0,22.7273,saya ingin makan salad,saya ingin makan sesuatu
1,10,61.5385,kita harus saling membantu,saya ingin makan sesuatu
2,25,67.7419,apakah anda membutuhkan bantuan,saya ingin makan sesuatu
3,35,69.6970,saya tersesat di dekat rumah anda,saya ingin makan sesuatu
4,50,72.4138,pilihan anda banyak sekali ya,saya ingin makan sesuatu
5,65,75.0000,bagaimana kabarmu belakangan ini,saya ingin makan sesuatu
6,75,77.7778,waktu berjalan begitu cepat,saya ingin makan sesuatu
7,85,86.2069,tolong segera pergi dari sini,saya ingin makan sesuatu
8,95,94.7368,maaf saya terlambat,saya ingin makan sesuatu
9,100,128.5714,halo apa kabar,saya ingin makan sesuatu

==============================================================================================================
📄 File: complete_metrics_NOISE_BASELINE_all_eq_3_0_fixed_hilbert_test_predictions_1_1.csv
==============================================================================================================

,persentil,cer,sentence,prediction
0,0,50.0000,maaf telah mengganggu anda,maaf membuat anda
1,10,66.6667,saya sangat menghargai saran anda,maaf membuat anda
2,25,71.4286,makanan di sana lumayan enak,maaf membuat anda
3,35,72.2222,terima kasih banyak atas undangannya,maaf membuat anda
4,50,75.0000,kamu benar benar menjadi lebih sehat,maaf membuat anda
5,65,75.8621,pilihan anda banyak sekali ya,maaf membuat anda
6,75,77.7778,saya punya nomornya di sini,maaf membuat anda
7,85,80.5556,apakah anda tertarik dengan komputer,maaf membuat anda
8,95,84.6154,sepertinya kamu sedang flu,maaf membuat anda
9,100,131.2500,mari kita bicara,maaf teman saya sedang sakit

==============================================================================================================
📄 File: complete_metrics_NOISE_BASELINE_all_eq_3_0_hilbert_test_predictions_2_1_IndoGPT.csv
==============================================================================================================

,persentil,cer,sentence,prediction
0,0,21.7391,kamu akan segera sembuh,kami akan segera sampai
1,10,63.3333,mengapa kamu melakukan hal itu,saya ingin makan sesuatu
2,25,69.4444,kamu benar benar menjadi lebih sehat,saya ingin makan sesuatu
3,35,71.1111,dia tidak tahu bagaimana menghadapi kenyataan,kami akan segera sampai
4,50,73.3333,beberapa bulan terakhir ini kamu sangat sibuk,saya tidak sengaja bertemu teman lama
5,65,76.1905,dia sudah punya pacar,saya akan pergi
6,75,80.0000,apakah anda baik baik saja pak,saya tidak sengaja bertemu teman
7,85,84.2105,di mana alamat anda,kami akan segera sampai
8,95,96.6667,kurangi makan roti dan kentang,saya tidak sengaja bertemu teman lama
9,100,150.0000,mari kita bicara,saya tidak sengaja bertemu teman

==============================================================================================================
📄 File: complete_metrics_NOISE_BASELINE_all_eq_3_0_log-mel_test_predictions_6_1.csv
==============================================================================================================

,persentil,cer,sentence,prediction
0,0,22.7273,saya ingin makan salad,saya ingin makan sesuatu
1,10,66.6667,waktu berjalan begitu cepat,saya benar benar
2,25,70.2703,saya sedang terburu buru sampai jumpa,apa yang bisa dibantu
3,35,71.8750,cinta terkadang benar benar buta,dia membuat keputusan
4,50,75.0000,mari makan di luar malam ini,anda benar benar
5,65,76.9231,sepertinya kamu sedang flu,kamu benar benar
6,75,78.1250,anda ingin ayam atau daging sapi,apakah ada yang bisa dibantu
7,85,80.0000,dia sangat ketat terhadap kami,kamu adalah orang
8,95,86.3636,tersesat butuh bantuan,kami akan segera sampai
9,100,122.2222,cobalah besok pagi,selamat datang di kantor kami

==============================================================================================================
📄 File: complete_metrics_NOISE_BASELINE_all_eq_3_0_logmel_test_predictions_10_1_IndoGPT.csv
==============================================================================================================

,persentil,cer,sentence,prediction
0,0,22.7273,saya ingin makan salad,saya ingin makan sesuatu
1,10,61.5385,kita harus saling membantu,saya ingin makan sesuatu
2,25,67.7419,apakah anda membutuhkan bantuan,saya ingin makan sesuatu
3,35,69.6970,saya tersesat di dekat rumah anda,saya ingin makan sesuatu
4,50,72.4138,pilihan anda banyak sekali ya,saya ingin makan sesuatu
5,65,75.0000,bagaimana kabarmu belakangan ini,saya ingin makan sesuatu
6,75,77.7778,waktu berjalan begitu cepat,saya ingin makan sesuatu
7,85,86.2069,tolong segera pergi dari sini,saya ingin makan sesuatu
8,95,94.7368,maaf saya terlambat,saya ingin makan sesuatu
9,100,128.5714,halo apa kabar,saya ingin makan sesuatu