In [1]:
import os
import pandas as pd
from IPython.display import display

TARGET_METRIC = 'cer'

PERCENTILES = [0, 10, 25, 35, 50, 65, 75, 85, 95, 100]

PROJECT_ROOT = os.path.abspath(os.path.join(os.getcwd(), '../../../'))
DATA_DIR     = os.path.join(PROJECT_ROOT, 'experiments/ZuCo')

EXPERIMENTS = [
    {
        'exp': '2',
        'label': 'Exp 2 — ZGW | Log-Mel + Char LSTM (v6_1) | REAL',
        'file': 'complete_metrics_ZuCo_ZGW_NR_log-mel_fast_test_predictions_6_1.csv',
    },
    {
        'exp': '2',
        'label': 'Exp 2 — ZGW | Log-Mel + Char LSTM (v6_1) | NOISE BASELINE',
        'file': 'complete_metrics_ZuCo_NOISE_BASELINE_ZGW_NR_log-mel_fast_test_predictions_6_1.csv',
    },
    {
        'exp': '4',
        'label': 'Exp 4 — ALL | Log-Mel + Char LSTM (v6_1) | REAL',
        'file': 'complete_metrics_ZuCo_all_NR_log-mel_fast_test_predictions_6_1.csv',
    },
    {
        'exp': '4',
        'label': 'Exp 4 — ALL | Log-Mel + Char LSTM (v6_1) | NOISE BASELINE',
        'file': 'complete_metrics_ZuCo_NOISE_BASELINE_all_NR_log-mel_fast_test_predictions_6_1.csv',
    },
    {
        'exp': '5',
        'label': 'Exp 5 — ZGW | Hilbert + Char LSTM (v6_1) | REAL',
        'file': 'complete_metrics_ZuCo_ZGW_NR_hilbert_fast_test_predictions_6_1.csv',
    },
    {
        'exp': '5',
        'label': 'Exp 5 — ZGW | Hilbert + Char LSTM (v6_1) | NOISE BASELINE',
        'file': 'complete_metrics_ZuCo_NOISE_BASELINE_ZGW_NR_hilbert_fast_test_predictions_6_1.csv',
    },
    {
        'exp': '6',
        'label': 'Exp 6 — ZGW | Hilbert + GPT-2 Frozen (v10_1) | REAL',
        'file': 'complete_metrics_ZuCo_ZGW_NR_hilbert_GPT2_fast_test_predictions_10_1.csv',
    },
    {
        'exp': '6',
        'label': 'Exp 6 — ZGW | Hilbert + GPT-2 Frozen (v10_1) | NOISE BASELINE',
        'file': 'complete_metrics_ZuCo_NOISE_BASELINE_ZGW_NR_hilbert_GPT2_fast_test_predictions_10_1.csv',
    },
    {
        'exp': '10',
        'label': 'Exp 10 — ZGW | Log-Mel + GPT-2 Frozen (v13_1) | REAL',
        'file': 'complete_metrics_ZuCo_ZGW_NR_logmel_GPT2frozen_test_predictions.csv',
    },
    {
        'exp': '10',
        'label': 'Exp 10 — ZGW | Log-Mel + GPT-2 Frozen (v13_1) | NOISE BASELINE',
        'file': 'complete_metrics_ZuCo_NOISE_BASELINE_ZGW_NR_logmel_GPT2frozen_test_predictions.csv',
    },
]

print(f"Analisis Persentil — Metrik: {TARGET_METRIC.upper()}")
print(f"Direktori: {DATA_DIR}\n")

for exp in EXPERIMENTS:
    filepath = os.path.join(DATA_DIR, exp['file'])

    print("=" * 110)
    print(f"  {exp['label']}")
    print(f"  File: {exp['file']}")
    print("=" * 110)

    if not os.path.exists(filepath):
        print(f"  File tidak ditemukan: {filepath}\n")
        continue

    try:
        df = pd.read_csv(filepath)
    except Exception as e:
        print(f"  Gagal membaca file: {e}\n")
        continue

    req_cols = [TARGET_METRIC, 'sentence', 'prediction']
    missing  = [c for c in req_cols if c not in df.columns]
    if missing:
        print(f"  Kolom tidak ditemukan: {missing}\n")
        continue

    df_sorted = df.sort_values(by=TARGET_METRIC).reset_index(drop=True)
    n = len(df_sorted)

    if n == 0:
        print("  File CSV kosong.\n")
        continue

    rows = []
    for p in PERCENTILES:
        idx = int((p / 100.0) * (n - 1))
        row = df_sorted.iloc[idx]
        rows.append({
            'Persentil (%)':  p,
            TARGET_METRIC:    round(row[TARGET_METRIC], 4),
            'sentence':       row['sentence'],
            'prediction':     row['prediction'],
        })

    df_pct = pd.DataFrame(rows)
    pd.set_option('display.max_colwidth', 120)
    pd.set_option('display.width', 300)
    display(df_pct)
    print()

Analisis Persentil — Metrik: CER
Direktori: /workspace/EEG-to-Text_Conformer-Transducer/experiments/ZuCo

==============================================================================================================
  Exp 2 — ZGW | Log-Mel + Char LSTM (v6_1) | REAL
  File: complete_metrics_ZuCo_ZGW_NR_log-mel_fast_test_predictions_6_1.csv
==============================================================================================================

   Persentil (%)      cer                                                                                                                 sentence                                                                   prediction
0              0  68.6275  he worked a year for the accounting firm of price waterhouse in san francisco and then in august 1940 returned to ha...  he was a beat of his fordest rovester and the writers in mithatis on second
1             10  75.0000                                                                                     keynes was educated at oundle school                                                                 he was yedar
2             25  77.6224  in 1925 he joined the united states rubber company based in new york city as manager of the foreign division and mov...                                  gladbon he eals and as jone octine as tence
3             35  79.3548  she then appeared in minor roles in another four films until landing a supporting role under star roy rogers in a 19...                             his son albother general yorks and was a comeled
4             50  81.3953                                                                              huxley was born in godalming surrey england                                     chember of 199his mone robelit and rowed
5             65  83.6735                       he was also given a small part in star trek iii the search for spock as the excelsior helm officer                                                the puitorn on colander weres
6             75  85.3448     in 1940 he officially changed his name to david joseph manners and became a naturalized citizen of the united states                                                  gulde burs where he bestond
7             85  87.3874          clooneys first recordings in may of 1946 were for columbia records as a singer with the big band of tony pastor                                                           eincolacl romented
8             95  89.4231  during this time he worked on developing a federal system of roads canals bridges lighthouses and universities until...                                                  navil darwis the kency ston
9            100  93.0851  although ford is often credited with the idea contemporary sources indicate that the concept and its development cam...                                                            in 1958 and maryt

==============================================================================================================
  Exp 2 — ZGW | Log-Mel + Char LSTM (v6_1) | NOISE BASELINE
  File: complete_metrics_ZuCo_NOISE_BASELINE_ZGW_NR_log-mel_fast_test_predictions_6_1.csv
==============================================================================================================

   Persentil (%)      cer                                                                                                                 sentence                                             prediction
0              0  67.7419                                                           he later became president of the united secularists of america                    engles and samey president of phary
1             10  73.4694                       he was also given a small part in star trek iii the search for spock as the excelsior helm officer  and the company in the congertear of miguser buth and
2             25  77.5281                                her family lived in mcgehee arkansas where she was raised until they moved to little rock                  bether and presidental in the company
3             35  78.4091                                 senator from connecticut and a wall street executive banker with brown brothers harriman                    stailed an mection bescient suciety
4             50  82.0513                                           he graduated from harvard university in 1787 and was elected to phi beta kappa                              cymones to was compesters
5             65  83.0846  he graduated in 1937 from the university of california berkeley with a degree in economics and philosophy and earned...           became in maryt and abelter niteld in states
6             75  85.4839  in 1894 following the failure of hermanns electrochemical business the einsteins moved from munich to pavia italy ne...                          berne and evident and william
7             85  86.5079  the following year bush was connecticut chairman of the united negro college fund and was one of the uncfs earliest ...                                he sond novemist fircan
8             95  89.1304  he is infamous for his 1994 appearance on saturday night live as he potrays mr armstrong a scoutmaster who is a pedo...                                  he post on the acters
9            100  91.0714                                                                 winthrop died at st briac sur mer ille et vilaine france                                                fromest

==============================================================================================================
  Exp 4 — ALL | Log-Mel + Char LSTM (v6_1) | REAL
  File: complete_metrics_ZuCo_all_NR_log-mel_fast_test_predictions_6_1.csv
==============================================================================================================

   Persentil (%)      cer                                                                                                                 sentence prediction
0              0  79.1667                                                                                                 his wife is barbara bush     he was
1             10  90.4762                                                                               king married coretta scott on june 18 1953     he was
2             25  92.9412                                    while franklin was finding himself in london deborah married a man named john rodgers     he was
3             35  93.6170                                                                          einstein married mileva maria on january 6 1903     he was
4             50  94.6903        he was the son of frederick v king of denmark and his first consort louisa daughter of george ii of great britain     he was
5             65  95.6522      he represented maryland in the continental congress and in the federal congress as both the representative and a us     he was
6             75  96.0784  kerouacs spontaneous confessional language style inspired other writers including tom robbins richard brautigan hunt...     he was
7             85  96.5986  marvin pierce bush born october 22 1956 is the youngest son of george h w bush and barbara pierce and brother of geo...     he was
8             95  97.4684  erdoan played semi professional football for 16 years and worked for istanbuls municipal transport company and becam...     he was
9            100  98.4496  during kerouacs time at columbia university burroughs and kerouac got into trouble with the law for failing to repor...     he was

==============================================================================================================
  Exp 4 — ALL | Log-Mel + Char LSTM (v6_1) | NOISE BASELINE
  File: complete_metrics_ZuCo_NOISE_BASELINE_all_NR_log-mel_fast_test_predictions_6_1.csv
==============================================================================================================

   Persentil (%)      cer                                                                                                                 sentence prediction
0              0  79.1667                                                                                                 his wife is barbara bush     he was
1             10  90.4762                                                                               king married coretta scott on june 18 1953     he was
2             25  92.9412                                    while franklin was finding himself in london deborah married a man named john rodgers     he was
3             35  93.6170                                                                          einstein married mileva maria on january 6 1903     he was
4             50  94.6903        he was the son of frederick v king of denmark and his first consort louisa daughter of george ii of great britain     he was
5             65  95.6522      he represented maryland in the continental congress and in the federal congress as both the representative and a us     he was
6             75  96.0784  kerouacs spontaneous confessional language style inspired other writers including tom robbins richard brautigan hunt...     he was
7             85  96.5986  marvin pierce bush born october 22 1956 is the youngest son of george h w bush and barbara pierce and brother of geo...     he was
8             95  97.4684  erdoan played semi professional football for 16 years and worked for istanbuls municipal transport company and becam...     he was
9            100  98.4496  during kerouacs time at columbia university burroughs and kerouac got into trouble with the law for failing to repor...     he was

==============================================================================================================
  Exp 5 — ZGW | Hilbert + Char LSTM (v6_1) | REAL
  File: complete_metrics_ZuCo_ZGW_NR_hilbert_fast_test_predictions_6_1.csv
==============================================================================================================

   Persentil (%)      cer                                                                                                                 sentence                                                         prediction
0              0  70.9677                                                           he later became president of the united secularists of america                           he was phringer many the shugas comtined
1             10  73.4694                       in 1954 she along with bing crosby danny kaye and nvera ellen starred in the movie white christmas  the actiman his mastanied stures was allyer and with son epeltian
2             25  78.5714                                                                 winthrop died at st briac sur mer ille et vilaine france                                                from 198t steman de
3             35  79.3103                                  he was first appointed to fill the senate seat of ernest lundeen who had died in office                                   amonit and george am bush enkers
4             50  81.6327                       he was also given a small part in star trek iii the search for spock as the excelsior helm officer                                 his grand a mectiole coldumin shot
5             65  83.0986                                                  in 1964 she went to reprise again shifting the next year to dot records                                                     he in the pary
6             75  84.1463                                       his brother julian huxley was a biologist also noted for his evolutionary theories                                                 shen oke commasnat
7             85  85.7143  following attendance at the marine officers school at port royal south carolina he served as a member of the marine ...                                   belk in senganciant lave and was
8             95  90.0498  he graduated in 1937 from the university of california berkeley with a degree in economics and philosophy and earned...                                              he diote and mestyars
9            100  92.0863  adams was elected to the us house of representatives in 1830 one of only two us presidents to serve in congress afte...                                                  born show in 1983

==============================================================================================================
  Exp 5 — ZGW | Hilbert + Char LSTM (v6_1) | NOISE BASELINE
  File: complete_metrics_ZuCo_NOISE_BASELINE_ZGW_NR_hilbert_fast_test_predictions_6_1.csv
==============================================================================================================

   Persentil (%)      cer                                                                                                                 sentence                            prediction
0              0  70.9677                                                           he later became president of the united secularists of america          he sale son of shory warting
1             10  75.6098                                       his brother julian huxley was a biologist also noted for his evolutionary theories    eventer of rays presinged postares
2             25  79.8246       they had five children after which they relocated to norwich vermont where bush was a captain of a militia company  adied sepinger of the seconder hored
3             35  82.0000                                                                       he obtained his degree at edinburgh medical school                          he samery if
4             50  83.8710                                                           elvis had a twin brother jesse garon presley who died at birth                    the parent in 1963
5             65  84.6939                       in 1954 she along with bing crosby danny kaye and nvera ellen starred in the movie white christmas            he was bark ong aurys 194t
6             75  86.0465                                                                              huxley was born in godalming surrey england                        the reversidet
7             85  87.8788  some say this was because of a bargain he struck with henry clay which put clay into office as his secretary of stat...             1933 president on sevolds
8             95  91.1290  in 1894 following the failure of hermanns electrochemical business the einsteins moved from munich to pavia italy ne...                        researd shores
9            100  98.0769  during this time he worked on developing a federal system of roads canals bridges lighthouses and universities until...                                  rays

==============================================================================================================
  Exp 6 — ZGW | Hilbert + GPT-2 Frozen (v10_1) | REAL
  File: complete_metrics_ZuCo_ZGW_NR_hilbert_GPT2_fast_test_predictions_10_1.csv
==============================================================================================================

   Persentil (%)      cer                                                                                                                 sentence              prediction
0              0  69.7674                                                                              huxley was born in godalming surrey england          was son as and
1             10  83.3333                                                             austin is a member of the left wing socialist campaign group  was president from son
2             25  86.4865          clooneys first recordings in may of 1946 were for columbia records as a singer with the big band of tony pastor        from born in the
3             35  87.8049                                       his brother julian huxley was a biologist also noted for his evolutionary theories           was president
4             50  89.6774  she then appeared in minor roles in another four films until landing a supporting role under star roy rogers in a 19...       as son and son of
5             65  91.8182           three us presidents franklin d roosevelt and both bushes george h w bush and george w bush are her descendants              heuary and
6             75  93.0348  he graduated in 1937 from the university of california berkeley with a degree in economics and philosophy and earned...        was president of
7             85  95.5556  miguel ferrer born february 7 1955 in santa monica california is a puerto rican american actor who is often cast in ...                hean and
8             95  97.7011                                  he was first appointed to fill the senate seat of ernest lundeen who had died in office                      he
9            100  98.2759     in 1940 he officially changed his name to david joseph manners and became a naturalized citizen of the united states                     was

==============================================================================================================
  Exp 6 — ZGW | Hilbert + GPT-2 Frozen (v10_1) | NOISE BASELINE
  File: complete_metrics_ZuCo_NOISE_BASELINE_ZGW_NR_hilbert_GPT2_fast_test_predictions_10_1.csv
==============================================================================================================

   Persentil (%)       cer                                                                                                                 sentence                      prediction
0              0   76.7442                                                                              huxley was born in godalming surrey england            was president in the
1             10   84.2466  in 1999 at the 41st grammy awards miguel was nominated for best spoken word album for children in disneys the lion k...  was born of president and born
2             25   91.0112                                her family lived in mcgehee arkansas where she was raised until they moved to little rock                    was born and
3             35   92.3077  in 1925 he joined the united states rubber company based in new york city as manager of the foreign division and mov...                     was the son
4             50   94.4444  the following year bush was connecticut chairman of the united negro college fund and was one of the uncfs earliest ...                        was born
5             65   96.0526                                             in the years between the wars henry ford supported adolf hitlers nazi regime                             was
6             75   96.5909                                 michael mcmanus born february 5 1959 is a syndicated columnist who wrote ethics religion                             and
7             85   97.0370  miguel ferrer born february 7 1955 in santa monica california is a puerto rican american actor who is often cast in ...                           in 18
8             95   97.7273                                 senator from connecticut and a wall street executive banker with brown brothers harriman                              as
9            100  100.0000                                                                        in the senate he was aligned with the federalists                             NaN

==============================================================================================================
  Exp 10 — ZGW | Log-Mel + GPT-2 Frozen (v13_1) | REAL
  File: complete_metrics_ZuCo_ZGW_NR_logmel_GPT2frozen_test_predictions.csv
==============================================================================================================

   Persentil (%)       cer                                                                                                                 sentence                                                                                prediction
0              0   64.5455           three us presidents franklin d roosevelt and both bushes george h w bush and george w bush are her descendants  his son george h w bush and grandson george w bush would both later become us presidents
1             10   71.4286                                                                        in the senate he was aligned with the federalists                                               his son george h w bush and grandson george
2             25   75.2874  another example of a player misjudged by the nfl he became an ironman of the american football league who never miss...  his son george h w bush and grandson george w bush would both later become us presidents
3             35   76.5306                       in 1954 she along with bing crosby danny kaye and nvera ellen starred in the movie white christmas  his son george h w bush and grandson george w bush would both later become us presidents
4             50   77.1930       they had five children after which they relocated to norwich vermont where bush was a captain of a militia company  his son george h w bush and grandson george w bush would both later become us presidents
5             65   79.7101  following the campaign king was instrumental in the founding of the southern christian leadership conference sclc in...  his son george h w bush and grandson george w bush would both later become us presidents
6             75   89.7436                                           he graduated from harvard university in 1787 and was elected to phi beta kappa  his son george h w bush and grandson george w bush would both later become us presidents
7             85  100.0000                                                       he was a working class jewish boy who grew up in brooklyn new york  his son george h w bush and grandson george w bush would both later become us presidents
8             95  121.4286                                                                 winthrop died at st briac sur mer ille et vilaine france  his son george h w bush and grandson george w bush would both later become us presidents
9            100  194.4444                                                                                     keynes was educated at oundle school  his son george h w bush and grandson george w bush would both later become us presidents

==============================================================================================================
  Exp 10 — ZGW | Log-Mel + GPT-2 Frozen (v13_1) | NOISE BASELINE
  File: complete_metrics_ZuCo_NOISE_BASELINE_ZGW_NR_logmel_GPT2frozen_test_predictions.csv
==============================================================================================================

   Persentil (%)       cer                                                                                                                 sentence                                                                                prediction
0              0   64.5455           three us presidents franklin d roosevelt and both bushes george h w bush and george w bush are her descendants  his son george h w bush and grandson george w bush would both later become us presidents
1             10   71.4286                                                                        in the senate he was aligned with the federalists                                               his son george h w bush and grandson george
2             25   75.2874  another example of a player misjudged by the nfl he became an ironman of the american football league who never miss...  his son george h w bush and grandson george w bush would both later become us presidents
3             35   76.5306                       in 1954 she along with bing crosby danny kaye and nvera ellen starred in the movie white christmas  his son george h w bush and grandson george w bush would both later become us presidents
4             50   77.1930       they had five children after which they relocated to norwich vermont where bush was a captain of a militia company  his son george h w bush and grandson george w bush would both later become us presidents
5             65   79.7101  following the campaign king was instrumental in the founding of the southern christian leadership conference sclc in...  his son george h w bush and grandson george w bush would both later become us presidents
6             75   89.7436                                           he graduated from harvard university in 1787 and was elected to phi beta kappa  his son george h w bush and grandson george w bush would both later become us presidents
7             85  100.0000                                                       he was a working class jewish boy who grew up in brooklyn new york  his son george h w bush and grandson george w bush would both later become us presidents
8             95  121.4286                                                                 winthrop died at st briac sur mer ille et vilaine france  his son george h w bush and grandson george w bush would both later become us presidents
9            100  194.4444                                                                                     keynes was educated at oundle school  his son george h w bush and grandson george w bush would both later become us presidents